# Generated by Django 6.0.3 on 2026-03-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='StartDate', null=True)),
                ('finishdate', models.DateTimeField(db_column='FinishDate')),
                ('status', models.IntegerField(db_column='Status')),
                ('ownerid', models.CharField(db_column='OwnerId', max_length=36)),
            ],
            options={
                'db_table': 'auction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('startprice', models.DecimalField(db_column='StartPrice', decimal_places=2, max_digits=18)),
                ('reserveprice', models.DecimalField(db_column='ReservePrice', decimal_places=2, max_digits=18)),
                ('currentprice', models.DecimalField(db_column='CurrentPrice', decimal_places=2, max_digits=18)),
                ('winnerid', models.CharField(blank=True, db_column='WinnerId', max_length=36, null=True)),
                ('exhibitiondate', models.DateTimeField(db_column='ExhibitionDate')),
            ],
            options={
                'db_table': 'lot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('accountbalance', models.DecimalField(db_column='AccountBalance', decimal_places=2, max_digits=18)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('hashedpassword', models.CharField(db_column='HashedPassword', max_length=255)),
                ('role', models.IntegerField(db_column='Role')),
                ('isblocked', models.BooleanField(db_column='IsBlocked')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='Value', decimal_places=2, max_digits=18)),
                ('placementdate', models.DateTimeField(db_column='PlacementDate')),
                ('lotid', models.ForeignKey(db_column='LotId', on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.lot')),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.user')),
            ],
            options={
                'db_table': 'bid',
                'managed': True,
            },
        ),
    ]
